//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFListas.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SP_ShowMuni", ReplyAction="http://tempuri.org/IService/SP_ShowMuniResponse")]
        System.Data.DataSet SP_ShowMuni(int departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SP_ShowMuni", ReplyAction="http://tempuri.org/IService/SP_ShowMuniResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SP_ShowMuniAsync(int departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SP_ShowAllMuni", ReplyAction="http://tempuri.org/IService/SP_ShowAllMuniResponse")]
        System.Data.DataSet SP_ShowAllMuni();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SP_ShowAllMuni", ReplyAction="http://tempuri.org/IService/SP_ShowAllMuniResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SP_ShowAllMuniAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SP_ShowDepa", ReplyAction="http://tempuri.org/IService/SP_ShowDepaResponse")]
        System.Data.DataSet SP_ShowDepa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SP_ShowDepa", ReplyAction="http://tempuri.org/IService/SP_ShowDepaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SP_ShowDepaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WFListas.Servicio.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WFListas.Servicio.IService>, WFListas.Servicio.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SP_ShowMuni(int departamento) {
            return base.Channel.SP_ShowMuni(departamento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SP_ShowMuniAsync(int departamento) {
            return base.Channel.SP_ShowMuniAsync(departamento);
        }
        
        public System.Data.DataSet SP_ShowAllMuni() {
            return base.Channel.SP_ShowAllMuni();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SP_ShowAllMuniAsync() {
            return base.Channel.SP_ShowAllMuniAsync();
        }
        
        public System.Data.DataSet SP_ShowDepa() {
            return base.Channel.SP_ShowDepa();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SP_ShowDepaAsync() {
            return base.Channel.SP_ShowDepaAsync();
        }
    }
}
